const constant = {

  RECENT_HOUR: 3,
  RECENT_DAY: 1,
  RECENT_WEEK: 1,
  RECENT_MONTH: 1,
  RECENT_YEAR: 1,

  GRANULARITY_HOUR: 300,
  GRANULARITY_DAY: 900,
  GRANULARITY_WEEK: 3600,
  GRANULARITY_MONTH: 21600,
  GRANULARITY_YEAR: 86400

};

module.exports = constant;
